name = "Turf"
uuid = "e89237b0-9201-11e9-31b0-6361926203f7"
authors = ["Filippo Nori <nori.filippo@gmail.com>"]
version = "0.2.1"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GeoInterface = "0.5"
GeoJSON = "0.5"
Reexport = "1"
julia = "1"
